package com.example.stockmanagementsystembackend.domain.inventory;

import com.example.stockmanagementsystembackend.domain.inventory.entity.InventoryItem;
import com.example.stockmanagementsystembackend.domain.inventory.repository.InventoryItemRepository;
import com.example.stockmanagementsystembackend.domain.inventory.service.InventoryItemService;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.test.context.SpringBootTest;
import org.springframework.jdbc.core.JdbcTemplate;
import org.springframework.transaction.annotation.Transactional;

import javax.sql.DataSource;
import java.util.List;

import static org.junit.jupiter.api.Assertions.*;

@SpringBootTest
@Transactional
class InventoryItemRepositoryTest {
    @Autowired private InventoryItemRepository repository;
    @Autowired private JdbcTemplate jdbc;
    @Autowired private DataSource dataSource;
    @Autowired private InventoryItemService service;

    @BeforeEach
    void fixture() throws Exception {
        // Explicit test fixtures only: refuse to run DDL against the shared MySQL schema.
        try (var connection = dataSource.getConnection()) {
            assertTrue(connection.getMetaData().getURL().startsWith("jdbc:h2:mem:"));
        }
        jdbc.execute("create table if not exists \"Category\" (category_id int primary key, name varchar(45), description clob)");
        jdbc.execute("create table if not exists \"UnitType\" (unit_type_id int primary key, name varchar(45))");
        jdbc.execute("""
                create table if not exists "InventoryItem" (
                    item_id int generated by default as identity primary key,
                    name varchar(60), category_id int not null references "Category"(category_id),
                    total_quantity double, unit_type_id int not null references "UnitType"(unit_type_id),
                    unit_price double, description clob, reorder_threshold double)
                """);
        jdbc.update("insert into \"Category\" values (101, 'Food', null), (102, 'Cleaning', null)");
        jdbc.update("insert into \"UnitType\" values (101, 'Kilogram')");
        jdbc.update("""
                insert into "InventoryItem" (item_id, name, category_id, total_quantity, unit_type_id, unit_price, reorder_threshold)
                values (101, 'Rice', 101, 10, 101, 250, 10),
                       (102, 'Brown RICE', 101, 11, 101, 300, 10),
                       (103, 'Soap', 102, 2, 101, 100, 5),
                       (104, 'Unknown quantity', 101, null, 101, 20, 10),
                       (105, 'Unknown threshold', 101, 1, 101, 20, null)
                """);
    }

    @Test
    void nameSearchIsCaseInsensitiveAndCategoryFilterUsesForeignKey() {
        assertEquals(List.of("Brown RICE", "Rice"), repository
                .findByNameContainingIgnoreCaseOrderByNameAsc("rIcE").stream().map(InventoryItem::getName).toList());
        assertEquals(List.of("Soap"), repository.findByCategory_CategoryIdOrderByNameAsc(102)
                .stream().map(InventoryItem::getName).toList());
        assertTrue(repository.findByNameContainingIgnoreCaseOrderByNameAsc("%").isEmpty());
    }

    @Test
    void lowStockIncludesEqualityAndExcludesUnknownValues() {
        assertEquals(List.of("Rice", "Soap"), repository.findLowStock().stream().map(InventoryItem::getName).toList());
    }

    @Test
    void lockedLookupCanPersistQuantityAndValuationIsNotAColumn() {
        InventoryItem item = repository.findByIdForUpdate(101).orElseThrow();
        item.setTotalQuantity(12.0);
        repository.saveAndFlush(item);
        assertEquals(12.0, jdbc.queryForObject("select total_quantity from \"InventoryItem\" where item_id = 101", Double.class));
        assertEquals(3000.0, item.calculateValuation());
        assertEquals(101, item.getCategoryId());
        assertEquals(101, item.getUnitTypeId());
    }

    @Test
    void serviceCrudResolvesRealForeignKeysAndPersistsToExactSchemaNames() {
        InventoryItem item = new InventoryItem();
        item.setName("  Flour  ");
        item.setCategoryId(101);
        item.setUnitTypeId(101);
        item.setTotalQuantity(5.0);
        item.setUnitPrice(30.0);
        item.setReorderThreshold(3.0);
        InventoryItem created = service.save(item);
        repository.flush();
        assertNotNull(created.getId());
        assertEquals("Flour", service.getById(created.getId()).getName());
        item.setName("Wheat flour");
        service.update(created.getId(), item);
        service.adjustQuantity(created.getId(), -2.0);
        repository.flush();
        assertTrue(service.getLowStock().stream().anyMatch(i -> i.getId().equals(created.getId())));
        service.delete(created.getId());
        assertFalse(repository.existsById(created.getId()));
    }
}
