package com.example.stockmanagementsystembackend.domain.stock;

import com.example.stockmanagementsystembackend.domain.stock.entity.Stock;
import com.example.stockmanagementsystembackend.domain.stock.repository.StockRepository;
import com.example.stockmanagementsystembackend.domain.stock.service.StockService;
import jakarta.persistence.EntityManager;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.beans.factory.annotation.Qualifier;
import org.springframework.boot.test.context.SpringBootTest;
import org.springframework.jdbc.core.JdbcTemplate;
import org.springframework.transaction.annotation.Transactional;
import org.springframework.web.server.ResponseStatusException;

import javax.sql.DataSource;
import java.time.Clock;
import java.time.LocalDate;
import java.util.List;
import java.util.Set;

import static org.junit.jupiter.api.Assertions.*;

@SpringBootTest
@Transactional
class StockRepositoryTest {
    @Autowired private StockService service;
    @Autowired private StockRepository repository;
    @Autowired private JdbcTemplate jdbc;
    @Autowired private DataSource dataSource;
    @Autowired private EntityManager entityManager;
    @Autowired @Qualifier("stockBatchClock") private Clock clock;

    @BeforeEach
    void fixture() throws Exception {
        // DDL here is exclusively an ephemeral test fixture, never the shared database.
        try (var connection = dataSource.getConnection()) {
            assertTrue(connection.getMetaData().getURL().startsWith("jdbc:h2:mem:"));
        }
        jdbc.execute("create table if not exists \"Branch\" (branch_id int primary key, name varchar(45), location varchar(45))");
        jdbc.execute("create table if not exists \"Category\" (category_id int primary key, name varchar(45), description clob)");
        jdbc.execute("create table if not exists \"UnitType\" (unit_type_id int primary key, name varchar(45))");
        jdbc.execute("""
                create table if not exists "InventoryItem" (
                    item_id int generated by default as identity primary key, name varchar(60),
                    category_id int not null references "Category"(category_id), total_quantity double,
                    unit_type_id int not null references "UnitType"(unit_type_id),
                    unit_price double, description clob, reorder_threshold double)
                """);
        jdbc.execute("""
                create table if not exists "Stock" (
                    stock_id int primary key, quantity double, manufacture_date date, expiry_date date,
                    branch_id int not null references "Branch"(branch_id))
                """);
        jdbc.execute("""
                create table if not exists stock_items (
                    stock_id int not null references "Stock"(stock_id),
                    item_id int not null references "InventoryItem"(item_id), primary key (stock_id, item_id))
                """);
        jdbc.update("insert into \"Branch\" values (401, 'Colombo', 'Colombo'), (402, 'Kandy', 'Kandy')");
        jdbc.update("insert into \"Category\" values (401, 'Food', null)");
        jdbc.update("insert into \"UnitType\" values (401, 'Kilogram')");
        jdbc.update("""
                insert into "InventoryItem" (item_id, name, category_id, unit_type_id, total_quantity)
                values (401, 'Rice', 401, 401, 100), (402, 'Flour', 401, 401, 200)
                """);
    }

    private Stock request(int id, Set<Integer> itemIds) {
        Stock stock = new Stock();
        stock.setStockId(id);
        stock.setBranchId(401);
        stock.setQuantity(10.0);
        stock.setManufactureDate(LocalDate.now(clock).minusDays(10));
        stock.setExpiryDate(LocalDate.now(clock).plusDays(10));
        stock.setItemIds(itemIds);
        return stock;
    }

    @Test
    void createUpdateAndDeleteMaintainJoinRowsWithoutChangingItemsOrBranches() {
        Stock created = service.save(request(501, Set.of(401, 402)));
        assertFalse(created.isNew());
        assertEquals(2, count("select count(*) from stock_items where stock_id=501"));
        entityManager.clear();
        Stock loaded = service.getById(501);
        assertFalse(loaded.isNew());
        assertEquals(Set.of(401, 402), loaded.getItemIds());
        assertTrue(entityManager.getEntityManagerFactory().getPersistenceUnitUtil().isLoaded(loaded, "items"));

        Stock update = request(501, Set.of(402));
        update.setQuantity(30.0);
        update.setBranchId(402);
        service.update(501, update);
        entityManager.clear();
        assertEquals(List.of(402), jdbc.queryForList("select item_id from stock_items where stock_id=501", Integer.class));
        assertEquals(30.0, service.getById(501).getQuantity());
        assertEquals(402, service.getById(501).getBranchId());

        service.delete(501);
        assertEquals(0, count("select count(*) from stock_items where stock_id=501"));
        assertFalse(repository.existsById(501));
        assertEquals(2, count("select count(*) from \"InventoryItem\" where item_id in (401,402)"));
        assertEquals(100.0, jdbc.queryForObject("select total_quantity from \"InventoryItem\" where item_id=401", Double.class));
        assertEquals(2, count("select count(*) from \"Branch\" where branch_id in (401,402)"));
    }

    @Test
    void branchAndItemQueriesKeepAllAssociatedItemIds() {
        service.save(request(501, Set.of(401, 402)));
        Stock otherBranch = request(502, Set.of(402));
        otherBranch.setBranchId(402);
        service.save(otherBranch);
        entityManager.clear();
        assertEquals(List.of(501), service.getByBranch(401).stream().map(Stock::getStockId).toList());
        assertEquals(List.of(501, 502), service.getByItem(402).stream().map(Stock::getStockId).toList());
        assertEquals(Set.of(401, 402), service.getByItem(401).get(0).getItemIds());
        assertEquals(2, service.getAll().size());
    }

    @Test
    void expiryWindowIncludesBothBoundariesAndExcludesExpiredAndUndatedBatches() {
        LocalDate today = LocalDate.now(clock);
        int[] offsets = {-1, 0, 30, 31};
        for (int i = 0; i < offsets.length; i++) {
            Stock stock = request(510 + i, Set.of(401));
            stock.setExpiryDate(today.plusDays(offsets[i]));
            service.save(stock);
        }
        Stock undated = request(514, Set.of(401));
        undated.setExpiryDate(null);
        service.save(undated);
        entityManager.clear();
        assertEquals(List.of(511, 512), service.getExpiring(30).stream().map(Stock::getStockId).toList());
        assertEquals(List.of(511), service.getExpiring(0).stream().map(Stock::getStockId).toList());
        assertEquals(List.of(510), service.getExpired().stream().map(Stock::getStockId).toList());
    }

    @Test
    void duplicateClientIdCannotOverwriteAnExistingBatch() {
        service.save(request(501, Set.of(401)));
        Stock duplicate = request(501, Set.of(402));
        duplicate.setQuantity(99.0);
        ResponseStatusException error = assertThrows(ResponseStatusException.class, () -> service.save(duplicate));
        assertEquals(409, error.getStatusCode().value());
        assertEquals(10.0, jdbc.queryForObject("select quantity from \"Stock\" where stock_id=501", Double.class));
        assertEquals(List.of(401), jdbc.queryForList("select item_id from stock_items where stock_id=501", Integer.class));
    }

    @Test
    void emptyItemListClearsAssociationsWithoutDeletingInventory() {
        service.save(request(501, Set.of(401, 402)));
        service.update(501, request(501, Set.of()));
        assertEquals(0, count("select count(*) from stock_items where stock_id=501"));
        assertTrue(repository.existsById(501));
        assertEquals(2, count("select count(*) from \"InventoryItem\" where item_id in (401,402)"));
    }

    private int count(String sql) { return jdbc.queryForObject(sql, Integer.class); }
}
