spring.application.name=Stock-Management-System-Backend

# MySQL Database Configuration
spring.datasource.url=jdbc:mysql://localhost:3306/se
spring.datasource.username=root
spring.datasource.password=1234
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# JPA / Hibernate Configuration
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true